### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by cnjack** [netroby/gosense#1]
1.界面设计需要更为的简介，bootstrap虽好，但是需要更好的应用
2.如果目标是更快以及简单，建议抛弃mysql
3.个人建议markdown
4.评论插件可以自己写的，like wordpress

**Comment by netroby** [comment]
Thanks, I will see how can i improve it.

**Comment by cnjack** [comment]
you can provide a rule than very body can write a template

**Comment by netroby** [comment]
The templates directory contains the all template we use. so you can rewrite them as you want
