### ISSUE TITLE
godep go build failed，How to fix it？

### ISSUE THREAD

**Issue by luckypoem** [netroby/gosense#14]
hi.

root@AR:~/go# go get github.com/tools/godep
root@AR:~/go# go get github.com/netroby/gosense
root@AR:~/go# godep go build
godep: No Godeps found (or in any parent directory)
root@AR:~/go#

What's going on？

**Comment by netroby** [comment]
Thanks for interesting . You should try the build scripts (Need docker).
./up.sh

https://github.com/netroby/gosense/blob/master/up.sh

**Comment by luckypoem** [comment]
hi.

[root@hu gosense]# ls
admin-controller.go  catlog.sh            Godeps               readme.md  up.sh
api.go               cmd                  graceful-restart.sh  rss.go
assets               config.toml.dist     LICENSE.txt          sql
base.go              front-controller.go  main.go              templates
[root@hu gosense]# ./up.sh
+ '[' '!' -f config.toml ']'
+ cp config.toml.dist config.toml
++ pwd
+ docker run --rm --name go-build -v /root/go:/go -v /root/gosense:/www golang sh -c 'cd /www ;go get -v ; go build -o /www/gosense '
Post http:///var/run/docker.sock/v1.19/containers/create?name=go-build: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?
[root@hu gosense]# ls /var/run/
console  faillock  netreport  sepermit  setrans  sshd.pid  syslogd.pid  utmp
[root@hu gosense]# find . -name docker.sock
[root@hu gosense]#

how to fix it?tks

**Comment by netroby** [comment]
Docker started first
do you started docker ?
service docker start
ps aux | grep docker 

check docker running or not

**Comment by luckypoem** [comment]
hi.

[root@hu ~]# service docker start
Starting cgconfig service: Error: cannot mount cpuset to /cgroup/cpuset: Invalid argument
/sbin/cgconfigparser; error loading /etc/cgconfig.conf: Cgroup mounting failed
Failed to parse /etc/cgconfig.conf or /etc/cgconfig.d      [FAILED]
Starting docker:	                                   [  OK  ]
[root@hu ~]# ps aux|grep docker
root      7061  0.0  0.1 103256   872 pts/0    S+   21:14   0:00 grep docker
[root@hu ~]# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
[root@hu ~]# docker -d
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
WARN[0000] You are running linux kernel version 2.6.32-042stab112.15, which might be unstable running docker. Please upgrade your kernel to 3.10.0. 
ERRO[0000] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded. 
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: inappropriate ioctl for device 
[root@hu ~]#

还得升级linux kernel.若有问题，再来请教

**Comment by netroby** [comment]
Due to golang.org was blocked by GFW, so many package will not be able to download during the building progress.
If you have a DigitalOcean vps or other oversea vps ,you may easy to build and running . 
Suggest you try on CentOS 7 Ubuntu 15.10

**Comment by luckypoem** [comment]
hi.

我升级失败。你是说 CentOS 7的内核肯定是v3.10.0以上吗

**Comment by netroby** [comment]
Yes.

**Comment by luckypoem** [comment]
hi.

重新搞了个kvm vps.要服务商升级kernel到v3.20,然后运行了一次./up.sh,提示没有mysql,于是运行命令：
apt-get install mysql-client mysql-server -y,然后再运行一次./up.sh,显示：
root@ar2:~/gosense# ./up.sh
+ '[' '!' -f config.toml ']'
++ pwd
+ docker run --rm --name go-build -v /root/go:/go -v /root/gosense:/www golang sh -c 'cd /www ;go get -v ; go build -o /www/gosense '
go install: no install location for directory /www outside GOPATH
	For more details see: go help gopath
++ grep gs_db
++ wc -l
++ docker ps -a
+ '[' 1 -le 0 ']'
++ docker ps -a
++ wc -l
++ grep gosense
+ '[' 0 -ge 1 ']'
++ pwd
+ docker run --restart=always -d -p 8080:8080 --link gs_db:db -v /root/gosense:/www --name gosense debian sh -c 'cd /www && /www/gosense'
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
Digest: sha256:2a5204f0a00510e9b99d7ec0fe40bea495b8e3630b820b04675488aad4188e06
Status: Downloaded newer image for debian:latest
db54e94bfcdc2d3c34f02d17df7238283f31880200303d4e008f995ce31a0a0a
root@ar2:~/gosense#

然后再本地机器访问，http://my-vps-ip:8080,可是什么也没显示，怎么回事呢？

**Comment by netroby** [comment]
can you run docker ps -a to see if the docker running correctly?

**Comment by luckypoem** [comment]
hi.

root@ar2:~# ps aux|grep docker
root      2374  0.2  5.0 168856 25908 ?        Sl   08:58   1:32 /usr/bin/docker daemon -p /var/run/docker.pid
root     11919  0.0  2.5  84072 12876 ?        Sl   09:44   0:03 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.17.0.3 -container-port 8080
root     12216  0.0  0.1   7832   840 pts/1    R+   19:42   0:00 grep docker
root@ar2:~# docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
db54e94bfcdc        debian                 "sh -c 'cd /www && /w"   9 hours ago         Up 9 hours          0.0.0.0:8080->8080/tcp   gosense
a8c0d1124902        netroby/docker-mysql   "/entrypoint.sh mysql"   10 hours ago        Up 10 hours         3306/tcp                 gs_db
root@ar2:~#

docker 是在后台运行中的。docker ps -a所显示的内容表明docker运行正常吗？

**Comment by netroby** [comment]
docker ps -a 
will show all the running container.

At least one MySQL db container (The database)
At least one gosense contain (The Httpd server)

**Comment by netroby** [comment]
Here is my docker running containers
```
huzhifeng@s ~/go/src/github.com/netroby/gosense (master) $ docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                   PORTS                    NAMES
ff180e83c621        debian                 "sh -c 'cd /www && /w"   19 seconds ago      Up 19 seconds            0.0.0.0:8080->8080/tcp   gosense
dbbb10c9ee77        netroby/docker-mysql   "/entrypoint.sh mysql"   2 weeks ago         Up 3 hours               3306/tcp                 gs_db

```

**Comment by luckypoem** [comment]
hi.

root@ar2:~# docker ps -a
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
db54e94bfcdc debian "sh -c 'cd /www && /w" 9 hours ago Up 9 hours 0.0.0.0:8080->8080/tcp gosense
a8c0d1124902 netroby/docker-mysql "/entrypoint.sh mysql" 10 hours ago Up 10 hours 3306/tcp gs_db
root@ar2:~#

我这里的docker ps -a显示的内容跟你的docker ps -a显示的内容是类似的啊。
但是访问http://my-vps-ip:8080,什么也没显示。不知何故？如何解决？

谢谢答复！

**Comment by netroby** [comment]
Can you show me  
```
docker logs --tail 800 gosense
```
I need to check the docker logs

**Comment by luckypoem** [comment]
hi.

内容太多，终端只能显示最后的屏幕的内容：
/usr/local/go/src/database/sql/sql.go:1706 (0x47d228)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x46abde)
/usr/local/go/src/runtime/panic.go:423 (0x43a709)
/usr/local/go/src/runtime/panic.go:42 (0x438dc9)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x44f63a)
/usr/local/go/src/database/sql/sql.go:1633 (0x47c632)
/www/front-controller.go:58 (0x4094dc)
	(*FrontController).HomeCtr: for rows.Next() {
/www/main.go:31 (0x40f82a)
	(*FrontController).HomeCtr-fm: r.GET("/", fc.HomeCtr)
/go/src/github.com/gin-gonic/gin/context.go:95 (0x498e2a)
/go/src/github.com/gin-gonic/contrib/sessions/sessions.go:65 (0x497ef3)
/go/src/github.com/gin-gonic/gin/context.go:95 (0x498e2a)
/go/src/github.com/gin-gonic/gin/logger.go:56 (0x4aa2d1)
/go/src/github.com/gin-gonic/gin/context.go:95 (0x498e2a)
/go/src/github.com/gin-gonic/gin/recovery.go:43 (0x4aae31)
/go/src/github.com/gin-gonic/gin/context.go:95 (0x498e2a)
/go/src/github.com/gin-gonic/gin/gin.go:294 (0x49f882)
/go/src/github.com/gin-gonic/gin/gin.go:275 (0x49f4b7)
/usr/local/go/src/net/http/server.go:1862 (0x5074ae)
/usr/local/go/src/net/http/server.go:1361 (0x504aee)
/usr/local/go/src/runtime/asm_amd64.s:1721 (0x46cf31)

Error 1049: Unknown database 'gosense'
2015/12/12 00:43:20 Panic recovery -> runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:423 (0x43a709)
/usr/local/go/src/runtime/panic.go:42 (0x438dc9)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x44f63a)
/usr/local/go/src/database/sql/sql.go:1706 (0x47d228)
/usr/local/go/src/runtime/asm_amd64.s:437 (0x46abde)
/usr/local/go/src/runtime/panic.go:423 (0x43a709)
/usr/local/go/src/runtime/panic.go:42 (0x438dc9)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x44f63a)
/usr/local/go/src/database/sql/sql.go:1633 (0x47c632)
/www/front-controller.go:58 (0x4094dc)
	(*FrontController).HomeCtr: for rows.Next() {
/www/main.go:31 (0x40f82a)
	(*FrontController).HomeCtr-fm: r.GET("/", fc.HomeCtr)
/go/src/github.com/gin-gonic/gin/context.go:95 (0x498e2a)
/go/src/github.com/gin-gonic/contrib/sessions/sessions.go:65 (0x497ef3)
/go/src/github.com/gin-gonic/gin/context.go:95 (0x498e2a)
/go/src/github.com/gin-gonic/gin/logger.go:56 (0x4aa2d1)
/go/src/github.com/gin-gonic/gin/context.go:95 (0x498e2a)
/go/src/github.com/gin-gonic/gin/recovery.go:43 (0x4aae31)
/go/src/github.com/gin-gonic/gin/context.go:95 (0x498e2a)
/go/src/github.com/gin-gonic/gin/gin.go:294 (0x49f882)
/go/src/github.com/gin-gonic/gin/gin.go:275 (0x49f4b7)
/usr/local/go/src/net/http/server.go:1862 (0x5074ae)
/usr/local/go/src/net/http/server.go:1361 (0x504aee)
/usr/local/go/src/runtime/asm_amd64.s:1721 (0x46cf31)

[GIN] 2015/12/12 - 00:43:20 | 404 |      18.684µs | 198.20.69.74:48251 |   GET     /robots.txt
[GIN] 2015/12/12 - 00:43:20 | 404 |          14µs | 198.20.69.74:48261 |   GET     /sitemap.xml
root@ar2:~#

这行：
Error 1049: Unknown database 'gosense'，难道需要我手动创建数据库gosense?

**Comment by netroby** [comment]
sql file not right imported. the sql file location at https://github.com/netroby/gosense/blob/master/sql/bak.sql

the auto script may not running correctly
https://github.com/netroby/gosense/blob/master/up.sh#L17

**Comment by luckypoem** [comment]
hi.

怎么导入这个bak.sql?

**Comment by luckypoem** [comment]
hi.

我第一次接触 docker，不知如何在docker下导入sql文件。还请指教指教。
非常感谢

**Comment by netroby** [comment]
My docker version
```
huzhifeng@s ~ $ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

```

cd the gosense directory
```
    docker cp sql/bak.sql gs_db:/root/
    docker exec gs_db sh -c "mysql < /root/bak.sql"
```

**Comment by luckypoem** [comment]
hi.

root@ar2:~# cd gosense
root@ar2:~/gosense# ls
admin-controller.go  cmd		  gosense	       rss.go
api.go		     config.toml	  graceful-restart.sh  sql
assets		     config.toml.dist	  LICENSE.txt	       templates
base.go		     front-controller.go  main.go	       up.sh
catlog.sh	     Godeps		  readme.md
root@ar2:~/gosense# docker cp sql/bak.sql gs_db:/root/
root@ar2:~/gosense# docker exec gs_db sh -c "mysql < /root/bak.sql"
sh: 1: cannot open /root/bak.sql: No such file
root@ar2:~/gosense# find . -name bak.sql
./sql/bak.sql
root@ar2:~/gosense# docker exec gs_db sh -c "mysql < sql/bak.sql"
sh: 1: cannot open sql/bak.sql: No such file
root@ar2:~/gosense#

你第二条命令有问题，不知如何解决？

非常感谢你的答复

**Comment by netroby** [comment]
What's your docker version. 
May because the first docker cp sql/bak.sql gs_db:/root/ not success
If success , the bak.sql file will located at /root/bak.sql

you can check it via
docker exec gs_db sh -c "ls -al /root/"

**Comment by luckypoem** [comment]
hi.

root@ar2:~# docker exec gs_db sh -c "ls -al /root/"
total 32
drwx------  5 root root 4096 Dec 11 09:39 .
drwxr-xr-x 23 root root 4096 Dec 28  2013 ..
drwx------  2 root root 4096 Dec 28  2013 .aptitude
-rw-------  1 root root 1831 Dec 14 09:53 .bash_history
-rw-r--r--  1 root root  570 Jan 31  2010 .bashrc
-rw-r--r--  1 root root  140 Nov 19  2007 .profile
drwxr-xr-x  3 root root 4096 Dec 11 09:39 go
drwxr-xr-x  8 root root 4096 Dec 11 09:44 gosense
root@ar2:~# docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:06:12 UTC 2015
 OS/Arch:      linux/amd64
root@ar2:~#

"docker version"显示的内容跟你的差不多。docker exec gs_db sh -c "ls -al /root/"所显示的内容说明
”docker cp sql/bak.sql gs_db:/root/“未运行成功吗？可我运行它后，无出错提示呢？

谢谢回复！

**Comment by netroby** [comment]
Check if there a file location sql/bak.sql

**Comment by netroby** [comment]
Or you can using phpmyadmin or Mysql workbench to connection the mysql ip:port to manually import sql file into the mysql container

to get the mysql container ip, you can run  docker inspect gs_db | grep -i ipaddress

**Comment by luckypoem** [comment]
hi.

root@ar2:~/gosense# ls
admin-controller.go  cmd		  gosense	       rss.go
api.go		     config.toml	  graceful-restart.sh  sql
assets		     config.toml.dist	  LICENSE.txt	       templates
base.go		     front-controller.go  main.go	       up.sh
catlog.sh	     Godeps		  readme.md
root@ar2:~/gosense# ls sql
bak.sql
root@ar2:~/gosense# docker inspect gs_db | grep -i ipaddress
        "SecondaryIPAddresses": null,
        "IPAddress": "172.17.0.2",
                "IPAddress": "172.17.0.2",
root@ar2:~/gosense#
root@ar2:~/gosense# docker exec gs_db sh -c "mysql < sql/bak.sql"
sh: 1: cannot open sql/bak.sql: No such file
root@ar2:~/gosense#

真是很奇怪，明明有sql/bak.sql文件，怎么提示No such file？
“connect the mysql ip:port to manually import sql file into the mysql container”－具体的命令是什么？我的mysql container创建成功了吗？（我怀疑未创建成功），如果成功了，其端口号是什么？
谢谢答复

**Comment by netroby** [comment]
The mysql server port will be 172.17.0.2:3306 
you can test it via telnet 172.17.0.2:3306
or using mysql client

mysql -u root -h 172.17.0.2

**Comment by luckypoem** [comment]
hi.

root@ar2:~/gosense# mysql -u root -h 172.17.0.2 < sql/bak.sql
root@ar2:~/gosense#

然后呢？十分抱歉打扰你这么多

**Comment by netroby** [comment]
if sql import success.gosense will running well.
can you see it in browser?

**Comment by luckypoem** [comment]
hi.

 果然可访问了：http://155.94.137.32:8080，如何发帖／更新博客呢？

**Comment by netroby** [comment]
the admin login url will be /admin/login
and the admin user and password will be your config.toml
open it and you will see it

**Comment by netroby** [comment]
Add one blog ,you may visit http://155.94.137.32:8080/admin/addblog

**Comment by luckypoem** [comment]
怎么改端口8080为其他端口？
怎么改登陆密码？我修改了密码，并未生效。

**Comment by netroby** [comment]
If you want change port , you need read docker document, the up.sh show you the example how to run gosense inside container with 8080 port. the -p 8080:8080 may change to other port, like -p 80:8080, which will run gosense at 80 port

to change password, modify config.toml, and restart gosense by running docker restart gosense. then gosense will reload config file
