### ISSUE TITLE
在导入数据库时，遇错

### ISSUE THREAD

**Issue by luckypoem** [netroby/gosense#19]
hi.

我克隆了https://github.com/netroby/gosense/tree/storage/swift：
git clone --branch storage/swift https://github.com/netroby/gosense/
不过在导入数据库时，遇错：
root@AR:~/gosense# mysql -uroot -pmy_password gosense < sql/bak.sql
ERROR 1067 (42000) at line 3: Invalid default value for 'publish_time'
root@AR:~/gosense# 

如何解决？谢谢你。

root@AR:~/gosense# cat config.toml
# db_host = "gs_db"

db_host = "localhost"
db_port = 3306
db_name = "gosense"
db_user = "root"
db_password = "my_password"
admin_user = "admin"
admin_password = "s3curity"
site_name = "Hard Coder"
site_description = "Linux, opensource, golang"
# [object_storage]
# api_user = "userismyname@gmail.com"
# api_key = "************************"
# api_key = "qwrtyadwg"
# api_auth = "https://auth.runabove.io/v2.0"
# api_tenant = "ddddddddddddddddddddddddddddddddddddddd23434"
# api_region = "SBG-1"
# api_container = "test"
# api_cdn_url = "https://cdn.netroby.com/"

root@AR:~/gosense#

**Comment by netroby** [comment]
您好,不好意思,现在才看到. 这个问题大概是因为mysql版本的问题.

您试着用MySQL 5.7试试, publish_time这个字段,是datetime类型, 我默认设置为当前的时间(发布文章用到这个时间)

低版本的MySQL可能不支持

**Comment by luckypoem** [comment]
hi.

root@AR:~# mysql -uroot -pmy_pw
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 9
Server version: 5.7.18 Source distribution

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.
段错误
root@AR:~#

看样子，编译mysql-5.7.18失败。编译mysql-5.7.18不容易。
你能写篇编译mysql-5.7.18的文章吗

**Comment by netroby** [comment]
Hello, 您这边方便用docker么? docker启动mysql, 会非常便捷. 不用编译.

**Comment by netroby** [comment]
另外mysql官方应该有编译好的软件包,rpm, deb应该都有. 可以根据需要下载官方的软件包来安装

**Comment by luckypoem** [comment]
我到一个装了docker的vps.

git clone https://github.com/netroby/gosense
cd gosense
docker-compose up --build
遇错：
...
ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint gosense_web_1 (8ccba73ec8a9cb7fead88557950748161b1c48f8cd76d96a0a7a547d0fc9e9ad): Bind for 0.0.0.0:8080 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
root@localhost:~/gosense# netstat -lntp|grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN      26076/docker-proxy
root@localhost:~/gosense# lsof -i:8080
COMMAND     PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
docker-pr 26076 root    4u  IPv6 3280187      0t0  TCP *:http-alt (LISTEN)
root@localhost:~/gosense# kill 26076
root@localhost:~/gosense# docker-compose up --build
Building db
Step 1 : FROM mysql:5.7
 ---> e799c7f9ae9c
Step 2 : ADD ./sql /docker-entrypoint-initdb.d
 ---> Using cache
 ---> a4e98ef449c5
Successfully built a4e98ef449c5
Building web
Step 1 : FROM golang:1.7
 ---> 13b95d609715
Step 2 : ADD . /go/src/gosense/
 ---> Using cache
 ---> a689d697e4cf
Step 3 : WORKDIR /go/src/gosense
 ---> Using cache
 ---> 5d13c67258ad
Step 4 : RUN go get -v -d ... ;         go get -v github.com/jteeuwen/go-bindata/...;         go get -v github.com/elazarl/go-bindata-assetfs/...;         go-bindata-assetfs assets/... templates/...;         go build -ldflags "-linkmode external -extldflags -static" -v
 ---> Using cache
 ---> 45d104b92dba
Step 5 : CMD /go/src/gosense/gosense
 ---> Using cache
 ---> bf64d48f387f
Successfully built bf64d48f387f
gosense_db_1 is up-to-date
Starting gosense_web_1

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint gosense_web_1 (dd5e8cd1170453f56955c13dd8335d9decc48bc6166ddd44bb764ca8a325e79e): Bind for 0.0.0.0:8080 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
root@localhost:~/gosense# lsof -i:8080
root@localhost:~/gosense#

我杀死了占用8080端口的进程，然后再次运行docker-compose up --build
怎么还是显示port is already allocated呢？

**Comment by luckypoem** [comment]
hello.

"我杀死了占用8080端口的进程，然后再次运行docker-compose up --build
怎么还是显示port is already allocated呢？"
可否答复我呢？
非常感谢。

**Comment by netroby** [comment]
端口被占用了. 显示这个的原因,应该是有进程占用了8080端口. 解决办法,可以换一个端口,或者杀掉8080端口的监听daemon

**Comment by luckypoem** [comment]
root@localhost:~/gosense# ./graceful-restart.sh
+ '[' '!' -f config.toml ']'
+ '[' '!' -z ']'
++ docker exec gosense pidof gosense
Error response from daemon: Container c96368e6a8dec13e85ea2b77283c792b07692152a06d5952f27734b5a52ee937 is not running
+ PIDGS=
root@localhost:~/gosense#

怎么解决？
谢谢你

**Comment by netroby** [comment]
您好，看起来这个容器没有正确启动

**Comment by netroby** [comment]
接下来，我准备优化gosense安装体验， 不依赖mysql服务，内建sqlite支持

**Comment by luckypoem** [comment]
期待中。

**Comment by luckypoem** [comment]
我以前问过你的：https://github.com/netroby/gosense/issues/14 。不过那时没使用docker-compose up --build这种做法而搭建成功。现在使用docker-compose up --build这种做法，反而失败。可否恢复原来的做法？或把原来的做法的代码放在另一个分支下？

**Comment by netroby** [comment]
https://github.com/netroby/gosense/releases/tag/0.1.0.9

This release fixed the docker-compose problem , now you may have a try.

Require docker-engine 17.06ce, docker-compose 1.9+

Tested under centos7+docker-engine 17.06 + docker-compose 1.9
