### ISSUE TITLE
运行docker-compose up --build遇错，提示“./vol/config.toml: no such file or directory”

### ISSUE THREAD

**Issue by briteming** [netroby/gosense#28]
hi.

/go/src/gosense/main.go:115 +0x37 
web_1  | panic: open ./vol/config.toml: no such file or directory
web_1  | 
web_1  | goroutine 1 [running]:
web_1  | main.GetConfig(0x0)
web_1  | 	/go/src/gosense/main.go:93 +0x1a0
web_1  | main.main()
web_1  | 	/go/src/gosense/main.go:115 +0x37
web_1  | panic: open ./vol/config.toml: no such file or directory
web_1  | 
web_1  | goroutine 1 [running]:
web_1  | main.GetConfig(0x0)
web_1  | 	/go/src/gosense/main.go:93 +0x1a0
web_1  | main.main()
web_1  | 	/go/src/gosense/main.go:115 +0x37
web_1  | panic: open ./vol/config.toml: no such file or directory
web_1  | 
web_1  | goroutine 1 [running]:
web_1  | main.GetConfig(0x0)
web_1  | 	/go/src/gosense/main.go:93 +0x1a0
web_1  | main.main()
web_1  | 	/go/src/gosense/main.go:115 +0x37
web_1  | panic: open ./vol/config.toml: no such file or directory
web_1  | 
web_1  | goroutine 1 [running]:
web_1  | main.GetConfig(0x0)
web_1  | 	/go/src/gosense/main.go:93 +0x1a0
web_1  | main.main()
web_1  | 	/go/src/gosense/main.go:115 +0x37
web_1  | panic: open ./vol/config.toml: no such file or directory
web_1  | 
web_1  | goroutine 1 [running]:
web_1  | main.GetConfig(0x0)
web_1  | 	/go/src/gosense/main.go:93 +0x1a0
web_1  | main.main()
web_1  | 	/go/src/gosense/main.go:115 +0x37
web_1  | panic: open ./vol/config.toml: no such file or directory
web_1  | 
web_1  | goroutine 1 [running]:
web_1  | main.GetConfig(0x0)
web_1  | 	/go/src/gosense/main.go:93 +0x1a0
web_1  | main.main()
web_1  | 	/go/src/gosense/main.go:115 +0x37
gosense_web_1 exited with code 2

Killing gosense_web_1  ... done
Killing gosense_db_1   ... done
root@wh:~/gosense#

怎么解决？

**Comment by netroby** [comment]
https://github.com/netroby/gosense/blob/master/config.toml.dist
项目根目录有提供一个示例config.toml.dist文件，把它重命名，放到vol/config.toml

记得修改其中的配置为你自己的

**Comment by netroby** [comment]
![screenshot of netroby_gosense_ a blog web app powered by golang document at https___gosense netroby com the author blog was an example](https://user-images.githubusercontent.com/278153/48313827-9f2f5a00-e5fc-11e8-9ea7-48d70930a77c.jpg)
